/** Frozen Alpha v1 declarations. No runtime implementation is supplied by G0. */
export type AccountId = string & { readonly accountId: unique symbol };
export type PersonaUid = string & { readonly personaUid: unique symbol };
export type GeneratorKey = string & { readonly generatorKey: unique symbol };
export type ReleaseId = string & { readonly releaseId: unique symbol };
export type SecretRef = string & { readonly secretRef: unique symbol };
export type FleetIntent = 'MANAGED' | 'EXCLUDED';
export type ListingObserved = 'PUBLIC' | 'UNLISTED' | 'UNKNOWN';
export type OperationPhase = 'PREPARED' | 'DISPATCHING' | 'APPLIED' | 'NOT_APPLIED' | 'UNCERTAIN' | 'FAILED' | 'HELD';
export type AiState = 'READY' | 'ACTIVE' | 'WAITING_HUMAN' | 'COMPLETED' | 'FAILED' | 'RECOVERING';
export type SourceStatus = 'BLOCKED' | 'IN_DEVELOPMENT' | 'READY';
export type FailureCode = 'INVALID_REQUEST' | 'STALE_REVISION' | 'STALE_BINDING' | 'UNSUPPORTED_CAPABILITY' | 'OWNERSHIP_UNKNOWN' | 'SOURCE_DRIFT' | 'CONFLICT' | 'RATE_LIMIT' | 'WAITING_HUMAN' | 'RECOVERY_HOLD' | 'NOT_APPLIED' | 'UNCERTAIN' | 'UNAVAILABLE';
export interface Failure { readonly code: FailureCode; readonly message: string; readonly retryable: boolean }
export type Result<T> = { readonly ok: true; readonly result: T; readonly revision: number } | { readonly ok: false; readonly error: Failure; readonly revision: number };
export interface MutationGuard { readonly expectedRevision: number; readonly accountBindingEpoch: number; readonly opId: string }
export interface AccountBinding { readonly accountId: AccountId; readonly personaUid: PersonaUid; readonly epoch: number }
export interface AccountRecord extends AccountBinding { readonly name: string; readonly sessionState: 'VERIFIED' | 'UNKNOWN' | 'WAITING_HUMAN'; readonly revision: number; readonly asOf: string }
export interface SourceBinding { readonly repository: string; readonly ref: 'main'; readonly root: string; readonly folder: string; readonly slug: GeneratorKey; readonly commitSha: string; readonly blobs: Readonly<Record<string, string>>; readonly status: SourceStatus; readonly releaseId: ReleaseId | null }
export interface GeneratorRecord { readonly key: GeneratorKey; readonly accountId: AccountId; readonly personaUid: PersonaUid; readonly accountBindingEpoch: number; readonly fleetIntent: FleetIntent; readonly listingObserved: ListingObserved; readonly deployState: string; readonly refreshState: string; readonly sourceBinding: SourceBinding | null; readonly releaseId: ReleaseId | null; readonly revision: number; readonly asOf: string; readonly attentionRefs: readonly string[] }
export interface DeployableFiles { readonly pjs: string; readonly html: string; readonly thumbnail: Uint8Array }
export interface ReleaseRecord { readonly releaseId: ReleaseId; readonly source: SourceBinding; readonly files: DeployableFiles; readonly createdAt: string }
export interface Operation { readonly opId: string; readonly kind: string; readonly targetKey: string; readonly sourceRevision: string | number; readonly accountBindingEpoch: number; readonly phase: OperationPhase; readonly startedAt: string; readonly result?: Readonly<Record<string, unknown>>; readonly remoteEvidence?: Readonly<Record<string, unknown>> }
export interface ProviderContext extends AccountBinding { readonly routeRevision: number; readonly capabilityRevision: number }
export interface ProviderMutation extends MutationGuard { readonly context: ProviderContext; readonly targetKey: GeneratorKey; readonly expectedSourceRevision: string | null }
export interface ProviderReadback { readonly sourceRevision: string | null; readonly files?: DeployableFiles; readonly listing: ListingObserved; readonly ownership: 'CONFIRMED' | 'UNKNOWN'; readonly asOf: string }
/** Account-scoped discovery identity; single-generator ProviderReadback remains unchanged. */
export interface AccountGeneratorEntry { readonly key: GeneratorKey; readonly readback: ProviderReadback }
export interface PerchanceAdapter { probe(context: ProviderContext): Promise<Result<readonly string[]>>; read(input: { context: ProviderContext; targetKey: GeneratorKey }): Promise<Result<ProviderReadback>>; observe(input: { context: ProviderContext; targetKey: GeneratorKey }): Promise<Result<ProviderReadback>>; listGenerators(input: { context: ProviderContext; cursor?: string }): Promise<Result<Page<AccountGeneratorEntry>>>; create(input: ProviderMutation): Promise<Result<ProviderReadback>>; save(input: ProviderMutation & { files: DeployableFiles }): Promise<Result<ProviderReadback>>; setListing(input: ProviderMutation & { listing: 'PUBLIC' | 'UNLISTED' }): Promise<Result<ProviderReadback>>; delete(input: ProviderMutation): Promise<Result<ProviderReadback>> }
export interface GitHubAdapter { snapshot(input: { repository: string; ref: 'main'; paths: readonly string[] }): Promise<Result<{ commitSha: string; blobs: Readonly<Record<string, string>> }>>; readBlob(input: { repository: string; blobSha: string }): Promise<Result<Uint8Array>>; commit(input: { repository: string; ref: 'main'; expectedHeadSha: string; expectedBlobs: Readonly<Record<string, string | null>>; files: Readonly<Record<string, Uint8Array>>; opId: string; secretRef: SecretRef }): Promise<Result<{ commitSha: string; blobs: Readonly<Record<string, string>> }>> }
export interface Page<T> { readonly items: readonly T[]; readonly cursor: string | null; readonly asOf: string }
export interface HealthyActiveClock { readonly checkpointAt: string; readonly healthyMilliseconds: number; readonly state: 'HEALTHY' | 'OUTAGE' | 'SHUTDOWN' | 'UNKNOWN'; readonly evidenceRefs: readonly string[] }
export interface RefresherCommentLedger { readonly targetKey: GeneratorKey; readonly insertionBytes: string; readonly insertionOffset: number; readonly sourceBeforeHash: string; readonly sourceAfterHash: string; readonly saveReceipt: string | null; readonly sourceRevision: string | null }
export interface VisibilityObservation { readonly key: GeneratorKey; readonly feedPosition: number | null; readonly renderedPosition: number | null; readonly status: 'VISIBLE' | 'NOT_VISIBLE' | 'LIKELY_FILTERED' | 'UNKNOWN'; readonly asOf: string; readonly evidenceRefs: readonly string[] }
export interface AiReviewRecord { readonly id: string; readonly key: GeneratorKey; readonly accountId: AccountId; readonly state: AiState; readonly sourceHash: string | null; readonly provenanceRefs: readonly string[]; readonly approvalRevision: number | null }
export interface AttentionRecord { readonly id: string; readonly targetKey: string; readonly code: FailureCode; readonly message: string; readonly createdAt: string; readonly acknowledgedAt: string | null }
export interface BackupManifest { readonly version: 1; readonly encrypted: false; readonly createdAt: string; readonly hashes: Readonly<Record<string, string>>; readonly absentItems: readonly { item: string; reason: string }[] }
/** Sensitive entries exist only in an explicitly operator-authorized local archive. */
export interface BackupBundle { readonly manifest: BackupManifest; readonly personaMonkey: Uint8Array; readonly alpha: Uint8Array; readonly authorizedSensitiveEntries?: Readonly<Record<string, Uint8Array>> }
export interface ServiceQuery { readonly key?: string; readonly accountId?: AccountId; readonly cursor?: string; readonly limit?: number }
export interface ServiceMutation extends MutationGuard { readonly key?: string; readonly accountId?: AccountId; readonly options?: Readonly<Record<string, unknown>> }
export interface Accounts { list(params: ServiceQuery): Promise<Result<Page<AccountRecord>>>; get(params: ServiceQuery): Promise<Result<AccountRecord>>; enroll(params: ServiceMutation): Promise<Result<AccountRecord>>; verifySession(params: ServiceMutation): Promise<Result<AccountRecord>>; previewRebind(params: ServiceQuery): Promise<Result<readonly string[]>>; rebind(params: ServiceMutation): Promise<Result<AccountRecord>> }
export interface Inventory { list(params: ServiceQuery): Promise<Result<Page<GeneratorRecord>>>; get(params: ServiceQuery): Promise<Result<GeneratorRecord>>; observe(params: ServiceMutation): Promise<Result<GeneratorRecord>>; setIntent(params: ServiceMutation): Promise<Result<GeneratorRecord>>; inspectDrift(params: ServiceQuery): Promise<Result<GeneratorRecord>>; previewDelete(params: ServiceQuery): Promise<Result<readonly string[]>>; delete(params: ServiceMutation): Promise<Result<GeneratorRecord>> }
export interface SourceCatalog { scan(params: ServiceQuery): Promise<Result<Page<SourceBinding>>>; get(params: ServiceQuery): Promise<Result<SourceBinding>>; bind(params: ServiceMutation): Promise<Result<SourceBinding>>; resolveRelease(params: ServiceQuery): Promise<Result<ReleaseRecord>> }
export interface Reservation { preview(params: ServiceQuery): Promise<Result<readonly string[]>>; reserve(params: ServiceMutation): Promise<Result<Operation>>; reconcile(params: ServiceMutation): Promise<Result<Operation>> }
export interface Deployer { prepare(params: ServiceMutation): Promise<Result<Operation>>; apply(params: ServiceMutation): Promise<Result<Operation>>; reconcile(params: ServiceMutation): Promise<Result<Operation>>; rollback(params: ServiceMutation): Promise<Result<Operation>> }
export interface AiReview { queue(params: ServiceQuery): Promise<Result<Page<AiReviewRecord>>>; get(params: ServiceQuery): Promise<Result<AiReviewRecord>>; start(params: ServiceMutation): Promise<Result<AiReviewRecord>>; recordReview(params: ServiceMutation): Promise<Result<AiReviewRecord>>; approveIntent(params: ServiceMutation): Promise<Result<AiReviewRecord>> }
export interface Refresher { status(params: ServiceQuery): Promise<Result<Page<GeneratorRecord>>>; configure(params: ServiceMutation): Promise<Result<Readonly<Record<string, number>>>>; setEligibility(params: ServiceMutation): Promise<Result<GeneratorRecord>>; planPass(params: ServiceQuery): Promise<Result<readonly GeneratorKey[]>> }
export interface Visibility { observeRecent(params: ServiceQuery): Promise<Result<Page<VisibilityObservation>>>; getPosition(params: ServiceQuery): Promise<Result<VisibilityObservation>>; collectStats(params: ServiceQuery): Promise<Result<Readonly<Record<string, number | null>>>> }
export interface Attention { list(params: ServiceQuery): Promise<Result<Page<AttentionRecord>>>; get(params: ServiceQuery): Promise<Result<AttentionRecord>>; acknowledge(params: ServiceMutation): Promise<Result<AttentionRecord>>; raise(params: ServiceMutation): Promise<Result<AttentionRecord>> }
export interface Backup { previewExport(params: ServiceQuery): Promise<Result<BackupManifest>>; export(params: ServiceMutation): Promise<Result<BackupBundle>>; previewRestore(params: { bundle: BackupBundle }): Promise<Result<BackupManifest>>; restore(params: ServiceMutation & { bundle: BackupBundle }): Promise<Result<{ recoveryState: 'RECOVERY_HOLD' }>>; retain(params: ServiceMutation): Promise<Result<{ removedDownloadIds: readonly number[]; warnings: readonly string[] }>> }
export interface Services { readonly accounts: Accounts; readonly inventory: Inventory; readonly sourceCatalog: SourceCatalog; readonly reservation: Reservation; readonly deployer: Deployer; readonly aiReview: AiReview; readonly refresher: Refresher; readonly visibility: Visibility; readonly attention: Attention; readonly backup: Backup }
export type UiCommand = { [S in keyof Services]: `${S}.${Extract<keyof Services[S], string>}` }[keyof Services];
export interface UiRequest { readonly v: 1; readonly requestId: string; readonly command: UiCommand; readonly params: Readonly<Record<string, unknown>>; readonly expectedRevision?: number }
export type UiResponse = Result<unknown> & { readonly requestId: string };
export type PersonaReadCommand = "system.describe" | "system.status" | "persona.list" | "persona.get" | "storage.inspect" | "route.list" | "route.get" | "userscript.list" | "userscript.get" | "userscript.artifact.list" | "userscript.artifact.get" | "persona.control.get" | "execution.list" | "execution.get" | "execution.result.get" | "workflow.list" | "workflow.get" | "workflow.jobs.list" | "workflow.jobs.get";
export type PersonaMutationCommand = "persona.create" | "persona.open" | "persona.updateIdentity" | "persona.archive" | "persona.destroy" | "storage.clearCookies" | "storage.clearSiteData" | "storage.fullWipe" | "route.assign" | "route.test" | "userscript.assign" | "userscript.unassign" | "userscript.artifact.install" | "userscript.artifact.assign" | "userscript.artifact.unassign" | "userscript.artifact.release" | "persona.control.acquire" | "persona.control.renew" | "persona.control.release" | "execution.input.begin" | "execution.input.append" | "execution.input.commit" | "execution.input.discard" | "execution.secret.stage" | "execution.secret.discard" | "execution.input.submit" | "execution.start" | "execution.result.ack" | "execution.cancel" | "execution.focus" | "workflow.create" | "workflow.update" | "workflow.delete" | "workflow.run" | "workflow.jobs.stop" | "workflow.jobs.clearFinished";
export type PersonaBrokerRequest = { readonly version: 1; readonly requestId: string; readonly params: Readonly<Record<string, unknown>> } & ({ readonly command: PersonaReadCommand; readonly operationId?: string } | { readonly command: PersonaMutationCommand; readonly operationId: string; readonly precondition: { readonly bootId: string; readonly revision: number } });
export interface PersonaBrokerResponse { readonly version: 1; readonly requestId: string; readonly operationId?: string; readonly bootId: string; readonly revision: number; readonly ok: boolean; readonly result?: unknown; readonly error?: { readonly code: string; readonly message: string; readonly retryable: boolean } }
/** Only command names in the frozen surface and existing PersonaMonkey broker are valid. */
export interface PersonaBroker { request(input: PersonaBrokerRequest): Promise<PersonaBrokerResponse>; subscribe(listener: (event: unknown) => void): () => void }
